name: Github Pages Deploy

on:
  push:
    branches:
      - "master"
env:
  HOST_URL: https://waronkhoff.github.io/mfe_wmf_host
  HEADER_URL: https://waronkhoff.github.io/mfe_wmf_header

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: npm install && npm run build
        env:
          HOST_URL: ${{ env.HOST_URL }}
          HEADER_URL: ${{ env.HEADER_URL }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.

